### ISSUE TITLE
CTRE 5.2.2.0

### ISSUE THREAD

**Issue by RobinsonZ** [flamingchickens1540/pandora-titan-2018#18]
If at all possible we might try to test CTRE 5.2.2.0 on Titan/Pandora. We would have to put it in manually as GradleRIO doesn't support it yet per Open-RIO/gradlerio#79 (pending further testing which we might be able to do). Of course, this comes after making sure everything is stable on Pandora for comps.

**Comment by edelmanjm** [comment]
why is this assigned to me lol

**Comment by RobinsonZ** [comment]
you pinged me about it

**Comment by edelmanjm** [comment]
cuz i'm not in the lab to do it lol
